name: fenv
channels:
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.1.1
  - numpy==1.16.4
  - pandas=0.24.2
  - scipy=1.3.0
  - mayavi=4.7.1
  - PyQt5=5.13.0
  - scikit-learn=0.21.2
  - tensorflow=2.0.0-beta1
  - tensorflow-graphics=1.0.0
  - graphviz=0.11.1
  - pydot=1.4.1
  - h5py=2.9.0
  - hyperas=0.4.1
  - nbconvert=5.5.0
  - scikit-image=0.15.0
  - trimesh=2.38.42
  - nbdime=1.0.5
  - jupyter-tensorboard=0.1.10
  - ipykernel=5.1.1
  - autograd=1.3